### ISSUE TITLE
Smart roll causes hidden overlay

### ISSUE THREAD

**Issue by DrPotatoNet** [Xiexe/XSOverlay-Issue-Tracker#91] opened 2020-09-07 02:41 UTC
**Describe the bug in detail:**
If you open layout with a smart roll angle and you tilt your head, it'll open layout mode, but without the ui, so you have to close it by toggling it again then make sure your head isn't tilted and open layout mode for ui to show
Note: keyboard still shows up for some reason

**Provide steps to reproduce the bug:**
Have a smart roll angle, tilt your head, and open layout mode.

**Expected behavior:**
Layout mode opens at an angle and shows ui

**Additional Information:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5180830/output_log.txt)

**Comment by Xiexe** [comment] 2020-09-07 03:00
Known, will be fixed tomorrow morning

**Comment by DrPotatoNet** [comment] 2020-09-07 04:09
As an additional note: 1 window has to be open and after the 2nd attempt at toggling layout mode while tilted, it will fail every time your head is tilted there after

**Comment by Xiexe** [comment] 2020-09-07 06:08
Yeah, the issue is that when toggling layout mode, it tries to cache some stuff for the overlays, mainly curvature, so that it can restore it when smart roll gets disabled again. 

It fails to do that because of a null ref, and because of that, nothing else can get enabled, because it can't continue. I'll probably be able to fix in within like 5 minutes of opening the project tomorrow :)

**Comment by Xiexe** [comment] 2020-09-07 17:51
Fixed in 374

**Closed by Xiexe** 2020-09-07 17:51 UTC
Labels: bug
