### ISSUE TITLE
Pinned windows switching to SteamVR Status

### ISSUE THREAD

**Issue by Skyrunner258** [Xiexe/XSOverlay-Issue-Tracker#83] opened 2020-07-25 10:24 UTC
**Describe the bug in detail:**

My pinned windows continue to periodically switch to the SteamVR Status window, forcing me to change them back to the correct window that I had pinned. I noticed this most times when my VR lagged and started to hang. 

**Provide steps to reproduce the bug:**
Pin a specific window and get the game to hang, forcing SteamVR Status to have an update of some sort

**Expected behavior:**
What do you expect to happen, rather than what does happen?

That my pinned windows would remain the same unless I specifically chose to change them. 

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture log in the XSOverlay install directory.
Please attach your logs to the issue.

[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4975380/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4975387/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4975388/uDesktopDuplication.log)

**Additional Information:**
Provide any additional information here.

**Comment by Xiexe** [comment] 2020-07-30 15:53
Looking in to this!

**Comment by Hurix** [comment] 2020-10-06 18:50
@Xiexe Any luck/update with this? I have it as well.

**Comment by Xiexe** [comment] 2020-10-06 19:51
I actually haven't personally been able to recreate this issue when I've tried to, spent many hours with Discord / Chrome captured on the back of my hand and pinned just to see if it would ever happen, and it never did. 

Not saying it's not an issue, just saying that I can't recreate it personally, which makes it harder to track down what the root of the problem is.

**Comment by Xiexe** [comment] 2020-10-06 20:07
If there's any more very detailed information you all can give on this it would be great, a 100% reproduce rate would help nail it down pretty quick.

**Comment by Xiexe** [comment] 2020-10-14 09:43
This should be fixed in the latest beta build!

**Closed by Xiexe** 2020-10-14 09:43 UTC
Labels: bug
