### ISSUE TITLE
Occasionally focus gets locked inside the current Chrome tab

### ISSUE THREAD

**Issue by bdunderscore** [Xiexe/XSOverlay-Issue-Tracker#74] opened 2020-07-03 23:06 UTC
**Describe the bug in detail:**
In some cases, mouse and keyboard focus gets 'locked' within the current open chrome tab. It's still possible to interact normally with that tab, but attempting to switch tabs, use the navigation bar, or switch to a different application fails.

In particular:

* Clicking within the content of a currently open tab works. In particular, if you have multiple chrome windows open and visible, you can interact with the content of any of them.
* Trying to click on the navigation bar or tabs fails (has no effect)
* Clicking the windows taskbar has no effect
* Opening the start menu with the windows key works, but immediately closes

When these symptoms are occurring, the same behavior can be observed in the steam desktop, or directly using the keyboard and mouse. Closing XSOverlay using the Steam Big Screen interface immediately resolves the issue. Additionally, closing the current chrome window with Alt-F4 can resolve the issue (it sometimes comes back if I reopen the window with Ctrl-Shift-T, but sometimes does not).

**Provide steps to reproduce the bug:**

I have not identified a consistent repro yet, but it occurs frequently (once every few hours I'd say). I'm using chrome beta: `Version 84.0.4147.68 (Official Build) beta (64-bit)`

It seems to have started around the time the big refactor update was released.

**Expected behavior:**
Focus should not be locked within chrome windows.

**Output Log:**
I don't have the timestamp of when this last occurred, next time it occurs I'll capture and attach them at the time of occurrence.

**Comment by Xiexe** [comment] 2020-07-05 19:38
I think I know the cause and will hopefully have a fix for it soon.

**Comment by Xiexe** [comment] 2020-07-07 19:16
If you could try out the beta branch and let me know if this issue persists that would be wonderful!

**Comment by bdunderscore** [comment] 2020-07-09 01:38
Unable to test because of #76

**Comment by Xiexe** [comment] 2020-07-11 21:26
Now that #76 has been patched, would you mind letting me know if this has been fixed? Thank you!

**Comment by bdunderscore** [comment] 2020-07-12 02:15
Reproducibility is low so it'll be a few days before I can be sure. I'll let you know if I see it happening on beta.

**Comment by Xiexe** [comment] 2020-07-18 01:15
Assuming this is fixed due to no further issue reported on Discord or git, closing issue for now!

**Closed by Xiexe** 2020-07-18 01:15 UTC
Labels: Completed, bug
