### ISSUE TITLE
Hand tracking updates at half rate

### ISSUE THREAD

**Issue by PoisonedPanther** [Xiexe/XSOverlay-Issue-Tracker#81] opened 2020-07-22 20:03 UTC
**Describe the bug in detail:**
Windows pinned to a hand only update at half the current refresh rate (seemingly with a minimum fps of 45)

**Provide steps to reproduce the bug:**
Pin a window to a hand, move it and notice that it stutters

**Expected behavior:**
The windows should move at the full refresh rate rather than half the refresh rate

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4962219/output_log.txt)

**Additional Information:**
I have an Oculus Rift S which runs at 80Hz, recording a video and counting frames shows 45 fps of movement on XSOverlay windows. I have also received recordings from a Valve Index user, and counting frames shows half of the current refresh rate to a minimum of 45 fps.

**Comment by Xiexe** [comment] 2020-07-22 20:10
This is actually intentional, not a bug. 

Currently things are updating at half the rate with a minimum of 45, you are correct.

The reason this is the case currently is to lower system resource usage, especially on 4c4t machines, where we seem to use a lot of CPU. 

I'm working on reducing CPU usage, across the board, but as of right now nothing that I'm doing really shows much of anything in the profiler, which leads me to believe that CPU usage is due to something else that I can't quite track down. 

Anyways, you are correct! There's a reason for it though! 

If desired, I can add an option to the settings to enable or disable this!

**Comment by PoisonedPanther** [comment] 2020-07-22 20:14
An option to disable it would be great! I can handle the extra CPU usage and would love smooth movement, this is currently my only issue with XSOverlay.

**Comment by Xiexe** [comment] 2020-07-22 20:15
I'll get the option in with the next patch cycle!

**Comment by popcorn9499** [comment] 2020-07-22 20:37
I am not sure which you would be doing and either or would be fine. I am honestly just throwing ideas at the wall here. 

either have options for specific framerates (might look bad if they aren't even multiples not 100% sure)
the other option is to have it be a toggle for half framerate quarter framerate and full framerate.  Might be worth playing around with to see what feels better. 

Hopefully this isn't too confusing

Love XSOverlay its pretty nice overall and the user interface is soo much easier to work with than the others that exist

**Comment by Xiexe** [comment] 2020-07-22 20:41
Right now I'd probably just be adding a toggle for half vs full, call it performance mode or something similar, and then try and really boil down where the extra CPU is going. 

Ideally, I wouldn't need to have the toggle at all, since in a perfect world, CPU usage would be much lower than it currently is.

**Comment by popcorn9499** [comment] 2020-07-22 20:48
Fair enough. I mean in a perfect world everyone would have 16 or 32 or even 128 core systems and performance wouldn't be a concern.

**Comment by Xiexe** [comment] 2020-07-30 15:46
Just updating you all on this issue;

I've completely reworked the entirety of the UI and that will be coming to the beta branch soon, once I re-implement a new method for attaching windows to hands / head. 

With the UI overhaul, I've added an internal dynamic refresh rate system for the overlay's textures. 

What this means is that any UI overlay that's being currently used or animating will update and render it's UI at 60fps.
Any UI overlay that is not currently being used will drop it's UI update rate to 5. 

This has severely reduced CPU usage, and has allowed me to completely get rid of the thing from before, meaning all tracking and positional updates now run at full hmd refresh rate. 

Desktop / Window captures texture updates still happen at normal speeds - that hasn't changed.

I'm seeing sub 2% CPU usage now, down from 3-4% at idle.

So, unfortunately, no performance mode toggle, instead I just optimized things a bit smarter. :)

**Comment by Xiexe** [comment] 2020-08-02 15:41
The beta branch is out and available if you'd like to give it a try - assuming nothing is super horribly wrong with the update rates on things, I'll probably be closing this issue :)

In order to swap to beta:

Right click XSOverlay on Steam.
Click Properties.
Click the Betas tab.
In the drop down, select beta-

**Comment by PoisonedPanther** [comment] 2020-08-04 20:25
Everything seems good with the beta! Thank you for fixing this :)

**Comment by Xiexe** [comment] 2020-08-06 22:42
Glad to hear it! Closing the issue!

**Closed by Xiexe** 2020-08-06 22:42 UTC
Labels: bug
